name: Enterprise Deployment
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@6945a070c9143b3956147a233357352329e46724
      - name: Setup Pages
        uses: actions/configure-pages@1f0c5cde4bc74c016c8106206c9b3628e8f79f4c
      - name: Upload artifact
        uses: actions/upload-pages-artifact@61b5a00c1d65191c990b728519967f854c866b61
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@5925e01c10d7a04944ec0a9b89736e47f70b796d
